config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :registrations => "users/registrations", :sessions => "users/sessions" }
  root 'main#index'
  
  resources :districts
  resources :parking_lots
  resources :rents
  resources :users

end

app/models/rent.rb
class Rent < ActiveRecord::Base
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController

  before_filter :authenticate_user!
  def index
    @rents = Rent.all
  end

  def new
    @rent = Rent.new
    @parking_lots = ParkingLot.all
  end
  
  def show
    @rent = Rent.find(params[:id])
  end

  def create
    rent = Rent.new(params_rent)
    parking_lot = ParkingLot.find(rent.parking_lot_id)
    rent.total_price = rent.hours*parking_lot.price
    rent.user_id = current_user.id
    rent.save
    redirect_to :action => :index
  end

  def edit
    @rent = Rent.find(params[:id])
  end

  def update
    rent = Rent.find(params[:id]).update_attributes(params_rent)
    redirect_to :action => :index
  end

  def destroy
    rent = Rent.destroy(params[:id])
    redirect_to :action => :index
  end

  private
  def params_rent
    params.require(:rent).permit(
      :description
    )
  end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/index.html.erb
<h1>Reservaciones realizadas</h1>
<a href="/rents/new" >Agregar Reservacion</a>
<table class="table table-hovered table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Distrito</th>
        <th>Estacionamiento</th>
        <th>Cliente</th>
        <th>Fecha</th>
        <th>Tiempo</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>        
    </thead>
    <tbody>
    <% @rents.each do |rent| %>    
    <tr>
        <td><%= rent.id %></td>
        <td><%= rent.district.name %></td>
        <td><%= rent.parking_lot %></td>
        <td><%= rent.user.name %></td>
        <td><%= rent.date %></td>
        <td><%= rent.minutes %></td>
        <td><%= link_to "Ver", rent %></td>
        <td><%= link_to "Editar", edit_rent_path(rent) %></td>
        <td><%= link_to "Eliminar", rent, method: :delete, data: { confirm: "Estas seguro?" } %></td>
    </tr>
    <% end %>
    </tbody>
    
</table>

app/views/rents/new.html.erb
<div class="col-md-12">
<fieldset>
      <div id="legend">
      <legend class="">
        <strong> Rentar un estacionamiento
      </legend>
    </div>    

<%= form_for(@rent) do |f| %>

<div class="row">

  <div class="col-md-6">
  
      <div class="control-group">
        <%= f.label :parking_lot, :class => "control-label", :value => "Estacionmiento" %><br />
        <%= f.select :parking_lot_id, @parking_lots.map { |p| [p.name, p.id] }, {:class => "form-control"} %>
      </div>
      <div class="control-group">
        <%= f.label :date, :class => "control-label", :value => "Fecha" %>
        <%= f.date_field :date, autofocus: true, :class => "form-control" %>
      </div>
      <div class="control-group">
        <%= f.label :hours, :class => "control-label", :value => "Horas" %>
        <%= f.text_field :hours, autofocus: true, :class => "form-control" %>
      </div>
  
  </div>

  
  <div class="row">
    <% if @rent.errors.any? %>
      <div id="errors">
        <% @rent.errors.full_messages.each do |msg| %>
        <p class="text text-warning"> <%= msg %> </p>
        <% end %>
      </div>
    <% end %>
  </div>
 

<% end %>


</fieldset>
</div>